#ifndef PATHPLANNING_GLOBAL_H
#define PATHPLANNING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PATHPLANNING_LIBRARY)
#  define PATHPLANNINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PATHPLANNINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PATHPLANNING_GLOBAL_H
